version: '3'
services:
  app:
    image: svsimeonoff/StudentRegistry:{tag}
    ports:
      - "3030:3030" # Map port 3030 on the host to port 3030 in the container
    environment:
      - NODE_ENV=production
